<?php

use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
    */
   public function run()
    {

    $cities =  [
            ['id' => 1, 'departments_id'=>5,    'name'=>'MEDELLÍN'],
            ['id' => 2, 'departments_id'=>5,    'name'=>'ABEJORRAL'],
            ['id' => 3, 'departments_id'=>5,    'name'=>'ABRIAQUÍ'],
            ['id' => 4, 'departments_id'=>5,    'name'=>'ALEJANDRÍA'],
            ['id' => 5, 'departments_id'=>5,    'name'=>'AMAGÁ'],
            ['id' => 6, 'departments_id'=>5,    'name'=>'AMALFI'],
            ['id' => 7, 'departments_id'=>5,    'name'=>'ANDES'],
            ['id' => 8, 'departments_id'=>5,    'name'=>'ANGELÓPOLIS'],
            ['id' => 9, 'departments_id'=>5,    'name'=>'ANGOSTURA'],
            ['id' => 10, 'departments_id'=>5,   'name'=>'ANORÍ'],
            ['id' => 11, 'departments_id'=>5,   'name'=>'SANTAFÉ DE ANTIOQUIA'],
            ['id' => 12, 'departments_id'=>5,   'name'=>'ANZA'],
            ['id' => 13, 'departments_id'=>5,   'name'=>'APARTADÓ'],
            ['id' => 14, 'departments_id'=>5,   'name'=>'ARBOLETES'],
            ['id' => 15, 'departments_id'=>5,   'name'=>'ARGELIA'],
            ['id' => 16, 'departments_id'=>5,   'name'=>'ARMENIA'],
            ['id' => 17, 'departments_id'=>5,   'name'=>'BARBOSA'],
            ['id' => 18, 'departments_id'=>5,   'name'=>'BELMIRA'],
            ['id' => 19, 'departments_id'=>5,   'name'=>'BELLO'],
            ['id' => 20, 'departments_id'=>5,   'name'=>'BETANIA'],
            ['id' => 21, 'departments_id'=>5,   'name'=>'BETULIA'],
            ['id' => 22, 'departments_id'=>5,   'name'=>'CIUDAD BOLÍVAR'],
            ['id' => 23, 'departments_id'=>5,   'name'=>'BRICEÑO'],
            ['id' => 24, 'departments_id'=>5,   'name'=>'BURITICÁ'],
            ['id' => 25, 'departments_id'=>5,   'name'=>'CÁCERES'],
            ['id' => 26, 'departments_id'=>5,   'name'=>'CAICEDO'],
            ['id' => 27, 'departments_id'=>5,   'name'=>'CALDAS'],
            ['id' => 28, 'departments_id'=>5,   'name'=>'CAMPAMENTO'],
            ['id' => 29, 'departments_id'=>5,   'name'=>'CAÑASGORDAS'],
            ['id' => 30, 'departments_id'=>5,   'name'=>'CARACOLÍ'],
            ['id' => 31, 'departments_id'=>5,   'name'=>'CARAMANTA'],
            ['id' => 32, 'departments_id'=>5,   'name'=>'CAREPA'],
            ['id' => 33, 'departments_id'=>5,   'name'=>'EL CARMEN DE VIBORAL'],
            ['id' => 34, 'departments_id'=>5,   'name'=>'CAROLINA'],
            ['id' => 35, 'departments_id'=>5,   'name'=>'CAUCASIA'],
            ['id' => 36, 'departments_id'=>5,   'name'=>'CHIGORODÓ'],
            ['id' => 37, 'departments_id'=>5,   'name'=>'CISNEROS'],
            ['id' => 38, 'departments_id'=>5,   'name'=>'COCORNÁ'],
            ['id' => 39, 'departments_id'=>5,   'name'=>'CONCEPCIÓN'],
            ['id' => 40, 'departments_id'=>5,   'name'=>'CONCORDIA'],
            ['id' => 41, 'departments_id'=>5,   'name'=>'COPACABANA'],
            ['id' => 42, 'departments_id'=>5,   'name'=>'DABEIBA'],
            ['id' => 43, 'departments_id'=>5,   'name'=>'DONMATÍAS'],
            ['id' => 44, 'departments_id'=>5,   'name'=>'EBÉJICO'],
            ['id' => 45, 'departments_id'=>5,   'name'=>'EL BAGRE'],
            ['id' => 46, 'departments_id'=>5,   'name'=>'ENTRERRIOS'],
            ['id' => 47, 'departments_id'=>5,   'name'=>'ENVIGADO'],
            ['id' => 48, 'departments_id'=>5,   'name'=>'FREDONIA'],
            ['id' => 49, 'departments_id'=>5,   'name'=>'FRONTINO'],
            ['id' => 50, 'departments_id'=>5,   'name'=>'GIRALDO'],
            ['id' => 51, 'departments_id'=>5,   'name'=>'GIRARDOTA'],
            ['id' => 52, 'departments_id'=>5,   'name'=>'GÓMEZ PLATA'],
            ['id' => 53, 'departments_id'=>5,   'name'=>'GRANADA'],
            ['id' => 54, 'departments_id'=>5,   'name'=>'GUADALUPE'],
            ['id' => 55, 'departments_id'=>5,   'name'=>'GUARNE'],
            ['id' => 56, 'departments_id'=>5,   'name'=>'GUATAPE'],
            ['id' => 57, 'departments_id'=>5,   'name'=>'HELICONIA'],
            ['id' => 58, 'departments_id'=>5,   'name'=>'HISPANIA'],
            ['id' => 59, 'departments_id'=>5,   'name'=>'ITAGUI'],
            ['id' => 60, 'departments_id'=>5,   'name'=>'ITUANGO'],
            ['id' => 61, 'departments_id'=>5,   'name'=>'JARDÍN'],
            ['id' => 62, 'departments_id'=>5,   'name'=>'JERICÓ'],
            ['id' => 63, 'departments_id'=>5,   'name'=>'LA CEJA'],
            ['id' => 64, 'departments_id'=>5,   'name'=>'LA ESTRELLA'],
            ['id' => 65, 'departments_id'=>5,   'name'=>'LA PINTADA'],
            ['id' => 66, 'departments_id'=>5,   'name'=>'LA UNIÓN'],
            ['id' => 67, 'departments_id'=>5,   'name'=>'LIBORINA'],
            ['id' => 68, 'departments_id'=>5,   'name'=>'MACEO'],
            ['id' => 69, 'departments_id'=>5,   'name'=>'MARINILLA'],
            ['id' => 70, 'departments_id'=>5,   'name'=>'MONTEBELLO'],
            ['id' => 71, 'departments_id'=>5,   'name'=>'MURINDÓ'],
            ['id' => 72, 'departments_id'=>5,   'name'=>'MUTATÁ'],
            ['id' => 73, 'departments_id'=>5,   'name'=>'NARIÑO'],
            ['id' => 74, 'departments_id'=>5,   'name'=>'NECOCLÍ'],
            ['id' => 75, 'departments_id'=>5,   'name'=>'NECHÍ'],
            ['id' => 76, 'departments_id'=>5,   'name'=>'OLAYA'],
            ['id' => 77, 'departments_id'=>5,   'name'=>'PEÑOL'],
            ['id' => 78, 'departments_id'=>5,   'name'=>'PEQUE'],
            ['id' => 79, 'departments_id'=>5,   'name'=>'PUEBLORRICO'],
            ['id' => 80, 'departments_id'=>5,   'name'=>'PUERTO BERRÍO'],
            ['id' => 81, 'departments_id'=>5,   'name'=>'PUERTO NARE'],
            ['id' => 82, 'departments_id'=>5,   'name'=>'PUERTO TRIUNFO'],
            ['id' => 83, 'departments_id'=>5,   'name'=>'REMEDIOS'],
            ['id' => 84, 'departments_id'=>5,   'name'=>'RETIRO'],
            ['id' => 85, 'departments_id'=>5,   'name'=>'RIONEGRO'],
            ['id' => 86, 'departments_id'=>5,   'name'=>'SABANALARGA'],
            ['id' => 87, 'departments_id'=>5,   'name'=>'SABANETA'],
            ['id' => 88, 'departments_id'=>5,   'name'=>'SALGAR'],
            ['id' => 89, 'departments_id'=>5,   'name'=>'SAN ANDRÉS DE CUERQUÍA'],
            ['id' => 90, 'departments_id'=>5,   'name'=>'SAN CARLOS'],
            ['id' => 91, 'departments_id'=>5,   'name'=>'SAN FRANCISCO'],
            ['id' => 92, 'departments_id'=>5,   'name'=>'SAN JERÓNIMO'],
            ['id' => 93, 'departments_id'=>5,   'name'=>'SAN JOSÉ DE LA MONTAÑA'],
            ['id' => 94, 'departments_id'=>5,   'name'=>'SAN JUAN DE URABÁ'],
            ['id' => 95, 'departments_id'=>5,   'name'=>'SAN LUIS'],
            ['id' => 96, 'departments_id'=>5,   'name'=>'SAN PEDRO DE LOS MILAGROS'],
            ['id' => 97, 'departments_id'=>5,   'name'=>'SAN PEDRO DE URABA'],
            ['id' => 98, 'departments_id'=>5,   'name'=>'SAN RAFAEL'],
            ['id' => 99, 'departments_id'=>5,   'name'=>'SAN ROQUE'],
            ['id' => 100,'departments_id'=>5,   'name'=>'SAN VICENTE'],
            ['id' => 101,'departments_id'=>5,   'name'=>'SANTA BÁRBARA'],
            ['id' => 102,'departments_id'=>5,   'name'=>'SANTA ROSA DE OSOS'],
            ['id' => 103,'departments_id'=>5,   'name'=>'SANTO DOMINGO'],
            ['id' => 104,'departments_id'=>5,   'name'=>'EL SANTUARIO'],
            ['id' => 105,'departments_id'=>5,   'name'=>'SEGOVIA'],
            ['id' => 106,'departments_id'=>5,   'name'=>'SONSON'],
            ['id' => 107,'departments_id'=>5,   'name'=>'SOPETRÁN'],
            ['id' => 108,'departments_id'=>5,   'name'=>'TÁMESIS'],
            ['id' => 109,'departments_id'=>5,   'name'=>'TARAZÁ'],
            ['id' => 110,'departments_id'=>5,   'name'=>'TARSO'],
            ['id' => 111,'departments_id'=>5,   'name'=>'TITIRIBÍ'],
            ['id' => 112,'departments_id'=>5,   'name'=>'TOLEDO'],
            ['id' => 113,'departments_id'=>5,   'name'=>'TURBO'],
            ['id' => 114,'departments_id'=>5,   'name'=>'URAMITA'],
            ['id' => 115,'departments_id'=>5,   'name'=>'URRAO'],
            ['id' => 116,'departments_id'=>5,   'name'=>'VALDIVIA'],
            ['id' => 117,'departments_id'=>5,   'name'=>'VALPARAÍSO'],
            ['id' => 118,'departments_id'=>5,   'name'=>'VEGACHÍ'],
            ['id' => 119,'departments_id'=>5,   'name'=>'VENECIA'],
            ['id' => 120,'departments_id'=>5,   'name'=>'VIGÍA DEL FUERTE'],
            ['id' => 121,'departments_id'=>5,   'name'=>'YALÍ'],
            ['id' => 122,'departments_id'=>5,   'name'=>'YARUMAL'],
            ['id' => 123,'departments_id'=>5,   'name'=>'YOLOMBÓ'],
            ['id' => 124,'departments_id'=>5,   'name'=>'YONDÓ'],
            ['id' => 125,'departments_id'=>5,   'name'=>'ZARAGOZA'],
            ['id' => 126,'departments_id'=>8,   'name'=>'BARRANQUILLA (DISTRITO E'],
            ['id' => 127,'departments_id'=>8,   'name'=>'BARANOA'],
            ['id' => 128,'departments_id'=>8,   'name'=>'CAMPO DE LA CRUZ'],
            ['id' => 129,'departments_id'=>8,   'name'=>'CANDELARIA'],
            ['id' => 130,'departments_id'=>8,   'name'=>'GALAPA'],
            ['id' => 131,'departments_id'=>8,   'name'=>'JUAN DE ACOSTA'],
            ['id' => 132,'departments_id'=>8,   'name'=>'LURUACO'],
            ['id' => 133,'departments_id'=>8,   'name'=>'MALAMBO'],
            ['id' => 134,'departments_id'=>8,   'name'=>'MANATI'],
            ['id' => 135,'departments_id'=>8,   'name'=>'PALMAR DE VARELA'],
            ['id' => 136,'departments_id'=>8,   'name'=>'PIOJO'],
            ['id' => 137,'departments_id'=>8,   'name'=>'POLO NUEVO'],
            ['id' => 138,'departments_id'=>8,   'name'=>'PONEDERA'],
            ['id' => 139,'departments_id'=>8,   'name'=>'PUERTO COLOMBIA'],
            ['id' => 140,'departments_id'=>8,   'name'=>'REPELON'],
            ['id' => 141,'departments_id'=>8,   'name'=>'SABANAGRANDE'],
            ['id' => 142,'departments_id'=>8,   'name'=>'SABANALARGA'],
            ['id' => 143,'departments_id'=>8,   'name'=>'SANTA LUCIA'],
            ['id' => 144,'departments_id'=>8,   'name'=>'SANTO TOMAS'],
            ['id' => 145,'departments_id'=>8,   'name'=>'SOLEDAD'],
            ['id' => 146,'departments_id'=>8,   'name'=>'SUAN'],
            ['id' => 147,'departments_id'=>8,   'name'=>'TUBARA'],
            ['id' => 148,'departments_id'=>8,   'name'=>'USIACURI'],
            ['id' => 149,'departments_id'=>11,  'name'=>'SANTA FE DE BOGOTA, D.C.'],
            ['id' => 150,'departments_id'=>11,  'name'=>'SANTAFE DE BOGOTA D.C.-CH'],
            ['id' => 151,'departments_id'=>11,  'name'=>'SANTAFE DE BOGOTA D.C.-SA'],
            ['id' => 152,'departments_id'=>11,  'name'=>'SANTAFE DE BOGOTA D.C.-SA'],
            ['id' => 153,'departments_id'=>11,  'name'=>'SANTAFE DE BOGOTA D.C.- U'],
            ['id' => 154,'departments_id'=>11,  'name'=>'SANTAFE DE BOGOTA D.C.-TU'],
            ['id' => 155,'departments_id'=>11,  'name'=>'SANTAFE DE BOGOTA D.C.-BO'],
            ['id' => 156,'departments_id'=>11,  'name'=>'SANTAFE DE BOGOTA D.C.-KE'],
            ['id' => 157,'departments_id'=>11,  'name'=>'SANTAFE DE BOGOTA D.C.-FO'],
            ['id' => 158,'departments_id'=>11,  'name'=>'SANTAFE DE BOGOTA D.C.-EN'],
            ['id' => 159,'departments_id'=>11,  'name'=>'SANTAFE DE BOGOTA D.C.-SU'],
            ['id' => 160,'departments_id'=>11,  'name'=>'SANTAFE DE BOGOTA D.C.-BA'],
            ['id' => 161,'departments_id'=>11,  'name'=>'SANTAFE DE BOGOTA D.C.-TE'],
            ['id' => 162,'departments_id'=>11,  'name'=>'SANTAFE DE BOGOTA D.C.-MA'],
            ['id' => 163,'departments_id'=>11,  'name'=>'SANTAFE DE BOGOTA D.C.-AN'],
            ['id' => 164,'departments_id'=>11,  'name'=>'SANTAFE DE BOGOTA D.C.-PU'],
            ['id' => 165,'departments_id'=>11,  'name'=>'SANTAFE DE BOGOTA D.C.-CA'],
            ['id' => 166,'departments_id'=>11,  'name'=>'SANTAFE DE BOGOTA D.C.-RA'],
            ['id' => 167,'departments_id'=>11,  'name'=>'SANTAFE DE BOGOTA D.C.-CI'],
            ['id' => 168,'departments_id'=>11,  'name'=>'SANTAFE DE BOGOTA D.C.-SU'],
            ['id' => 169,'departments_id'=>13,  'name'=>'CARTAGENA (DISTRITO TURIS'],
            ['id' => 170,'departments_id'=>13,  'name'=>'ACHI'],
            ['id' => 171,'departments_id'=>13,  'name'=>'ALTOS DEL ROSARIO'],
            ['id' => 172,'departments_id'=>13,  'name'=>'ARENAL'],
            ['id' => 173,'departments_id'=>13,  'name'=>'ARJONA'],
            ['id' => 174,'departments_id'=>13,  'name'=>'ARROYOHONDO'],
            ['id' => 175,'departments_id'=>13,  'name'=>'BARRANCO DE LOBA'],
            ['id' => 176,'departments_id'=>13,   'name'=>'CALAMAR'],
            ['id' => 177,'departments_id'=>13,   'name'=>'CANTAGALLO'],
            ['id' => 178,'departments_id'=>13,   'name'=>'CICUCO'],
            ['id' => 179,'departments_id'=>13,   'name'=>'CORDOBA'],
            ['id' => 180,'departments_id'=>13,   'name'=>'CLEMENCIA'],
            ['id' => 181,'departments_id'=>13,   'name'=>'EL CARMEN DE BOLIVAR'],
            ['id' => 182,'departments_id'=>13,   'name'=>'EL GUAMO'],
            ['id' => 183,'departments_id'=>13,   'name'=>'EL PENON'],
            ['id' => 184,'departments_id'=>13,   'name'=>'HATILLO DE LOBA'],
            ['id' => 185,'departments_id'=>13,   'name'=>'MAGANGUE'],
            ['id' => 186,'departments_id'=>13,   'name'=>'MAHATES'],
            ['id' => 187,'departments_id'=>13,   'name'=>'MARGARITA'],
            ['id' => 188,'departments_id'=>13,   'name'=>'MARIA LA BAJA'],
            ['id' => 189,'departments_id'=>13,   'name'=>'MONTECRISTO'],
            ['id' => 190,'departments_id'=>13,   'name'=>'MOMPOS'],
            ['id' => 191,'departments_id'=>13,   'name'=>'MORALES'],
            ['id' => 192,'departments_id'=>13,   'name'=>'PINILLOS'],
            ['id' => 193,'departments_id'=>13,   'name'=>'REGIDOR'],
            ['id' => 194,'departments_id'=>13,   'name'=>'RIO VIEJO'],
            ['id' => 195,'departments_id'=>13,   'name'=>'SAN CRISTOBAL'],
            ['id' => 196,'departments_id'=>13,   'name'=>'SAN ESTANISLAO'],
            ['id' => 197,'departments_id'=>13,   'name'=>'SAN FERNANDO'],
            ['id' => 198,'departments_id'=>13,   'name'=>'SAN JACINTO'],
            ['id' => 199,'departments_id'=>13,   'name'=>'SAN JACINTO DEL CAUCA'],
            ['id' => 200,'departments_id'=>13,   'name'=>'SAN JUAN NEPOMUCENO'],
            ['id' => 201,'departments_id'=>13,   'name'=>'SAN MARTIN DE LOBA'],
            ['id' => 202,'departments_id'=>13,   'name'=>'SAN PABLO'],
            ['id' => 203,'departments_id'=>13,   'name'=>'SANTA CATALINA'],
            ['id' => 204,'departments_id'=>13,   'name'=>'SANTA ROSA'],
            ['id' => 205,'departments_id'=>13,   'name'=>'SANTA ROSA DEL SUR'],
            ['id' => 206,'departments_id'=>13,   'name'=>'SIMITI'],
            ['id' => 207,'departments_id'=>13,   'name'=>'SOPLAVIENTO'],
            ['id' => 208,'departments_id'=>13,   'name'=>'TALAIGUA NUEVO'],
            ['id' => 209,'departments_id'=>13,   'name'=>'TIQUISIO (PUERTO RICO)'],
            ['id' => 210,'departments_id'=>13,   'name'=>'TURBACO'],
            ['id' => 211,'departments_id'=>13,   'name'=>'TURBANA'],
            ['id' => 212,'departments_id'=>13,   'name'=>'VILLANUEVA'],
            ['id' => 213,'departments_id'=>13,   'name'=>'ZAMBRANO'],
            ['id' => 214,'departments_id'=>15, 'name'=>'TUNJA'],
            ['id' => 215,'departments_id'=>15,  'name'=>'ALMEIDA'],
            ['id' => 216,'departments_id'=>15,  'name'=>'AQUITANIA'],
            ['id' => 217,'departments_id'=>15,  'name'=>'ARCABUCO'],
            ['id' => 218,'departments_id'=>15,  'name'=>'BELEN'],
            ['id' => 219,'departments_id'=>15,  'name'=>'BERBEO'],
            ['id' => 220,'departments_id'=>15,  'name'=>'BETEITIVA'],
            ['id' => 221,'departments_id'=>15,  'name'=>'BOAVITA'],
            ['id' => 222,'departments_id'=>15,   'name'=>'BOYACA'],
            ['id' => 223,'departments_id'=>15,   'name'=>'BRICENO'],
            ['id' => 224,'departments_id'=>15,   'name'=>'BUENAVISTA'],
            ['id' => 225,'departments_id'=>15,   'name'=>'BUSBANZA'],
            ['id' => 226,'departments_id'=>15,   'name'=>'CALDAS'],
            ['id' => 227,'departments_id'=>15,   'name'=>'CAMPOHERMOSO'],
            ['id' => 228,'departments_id'=>15,   'name'=>'CERINZA'],
            ['id' => 229,'departments_id'=>15,   'name'=>'CHINAVITA'],
            ['id' => 230,'departments_id'=>15,   'name'=>'CHIQUINQUIRA'],
            ['id' => 231,'departments_id'=>15,   'name'=>'CHISCAS'],
            ['id' => 232,'departments_id'=>15,   'name'=>'CHITA'],
            ['id' => 233,'departments_id'=>15,   'name'=>'CHITARAQUE'],
            ['id' => 234,'departments_id'=>15,   'name'=>'CHIVATA'],
            ['id' => 235,'departments_id'=>15,   'name'=>'CIENEGA'],
            ['id' => 236,'departments_id'=>15,   'name'=>'COMBITA'],
            ['id' => 237,'departments_id'=>15,   'name'=>'COPER'],
            ['id' => 238,'departments_id'=>15,   'name'=>'CORRALES'],
            ['id' => 239,'departments_id'=>15,   'name'=>'COVARACHIA'],
            ['id' => 240,'departments_id'=>15,   'name'=>'CUBARA'],
            ['id' => 241,'departments_id'=>15,   'name'=>'CUCAITA'],
            ['id' => 242,'departments_id'=>15,   'name'=>'CUITIVA'],
            ['id' => 243,'departments_id'=>15,   'name'=>'CHIQUIZA'],
            ['id' => 244,'departments_id'=>15,   'name'=>'CHIVOR'],
            ['id' => 245,'departments_id'=>15,   'name'=>'DUITAMA'],
            ['id' => 246,'departments_id'=>15,   'name'=>'EL COCUY'],
            ['id' => 247,'departments_id'=>15,   'name'=>'EL ESPINO'],
            ['id' => 248,'departments_id'=>15,   'name'=>'FIRAVITOBA'],
            ['id' => 249,'departments_id'=>15,   'name'=>'FLORESTA'],
            ['id' => 250,'departments_id'=>15,   'name'=>'GACHANTIVA'],
            ['id' => 251,'departments_id'=>15,   'name'=>'GAMEZA'],
            ['id' => 252,'departments_id'=>15,   'name'=>'GARAGOA'],
            ['id' => 253,'departments_id'=>15,   'name'=>'GUACAMAYAS'],
            ['id' => 254,'departments_id'=>15,   'name'=>'GUATEQUE'],
            ['id' => 255,'departments_id'=>15,   'name'=>'GUAYATA'],
            ['id' => 256,'departments_id'=>15,   'name'=>'GUICAN'],
            ['id' => 257,'departments_id'=>15,   'name'=>'IZA'],
            ['id' => 258,'departments_id'=>15,   'name'=>'JENESANO'],
            ['id' => 259,'departments_id'=>15,   'name'=>'JERICO'],
            ['id' => 260,'departments_id'=>15,   'name'=>'LABRANZAGRANDE'],
            ['id' => 261,'departments_id'=>15,   'name'=>'LA CAPILLA'],
            ['id' => 262,'departments_id'=>15,   'name'=>'LA VICTORIA'],
            ['id' => 263,'departments_id'=>15,   'name'=>'LA UVITA'],
            ['id' => 264,'departments_id'=>15,   'name'=>'VILLA DE LEIVA'],
            ['id' => 265,'departments_id'=>15,   'name'=>'MACANAL'],
            ['id' => 266,'departments_id'=>15,   'name'=>'MARIPI'],
            ['id' => 267,'departments_id'=>15,   'name'=>'MIRAFLORES'],
            ['id' => 268,'departments_id'=>15,   'name'=>'MONGUA'],
            ['id' => 269,'departments_id'=>15,   'name'=>'MONGUI'],
            ['id' => 270,'departments_id'=>15,   'name'=>'MONIQUIRA'],
            ['id' => 271,'departments_id'=>15,   'name'=>'MOTAVITA'],
            ['id' => 272,'departments_id'=>15,   'name'=>'MUZO'],
            ['id' => 273,'departments_id'=>15,   'name'=>'NOBSA'],
            ['id' => 274,'departments_id'=>15,   'name'=>'NUEVO COLON'],
            ['id' => 275,'departments_id'=>15,   'name'=>'OICATA'],
            ['id' => 276,'departments_id'=>15,   'name'=>'OTANCHE'],
            ['id' => 277,'departments_id'=>15,   'name'=>'PACHAVITA'],
            ['id' => 278,'departments_id'=>15,   'name'=>'PAEZ'],
            ['id' => 279,'departments_id'=>15,   'name'=>'PAIPA'],
            ['id' => 280,'departments_id'=>15,   'name'=>'PAJARITO'],
            ['id' => 281,'departments_id'=>15,   'name'=>'PANQUEBA'],
            ['id' => 282,'departments_id'=>15,   'name'=>'PAUNA'],
            ['id' => 283,'departments_id'=>15,   'name'=>'PAYA'],
            ['id' => 284,'departments_id'=>15,   'name'=>'PAZ DEL RIO'],
            ['id' => 285,'departments_id'=>15,   'name'=>'PESCA'],
            ['id' => 286,'departments_id'=>15,   'name'=>'PISBA'],
            ['id' => 287,'departments_id'=>15,   'name'=>'PUERTO BOYACA'],
            ['id' => 288,'departments_id'=>15,   'name'=>'QUIPAMA'],
            ['id' => 289,'departments_id'=>15,   'name'=>'RAMIRIQUI'],
            ['id' => 290,'departments_id'=>15,   'name'=>'RAQUIRA'],
            ['id' => 291,'departments_id'=>15,   'name'=>'RONDON'],
            ['id' => 292,'departments_id'=>15,   'name'=>'SABOYA'],
            ['id' => 293,'departments_id'=>15,   'name'=>'SACHICA'],
            ['id' => 294,'departments_id'=>15,   'name'=>'SAMACA'],
            ['id' => 295,'departments_id'=>15,   'name'=>'SAN EDUARDO'],
            ['id' => 296,'departments_id'=>15,   'name'=>'SAN JOSE DE PARE'],
            ['id' => 297,'departments_id'=>15,   'name'=>'SAN LUIS DE GACENO'],
            ['id' => 298,'departments_id'=>15,   'name'=>'SAN MATEO'],
            ['id' => 299,'departments_id'=>15,   'name'=>'SAN MIGUEL DE SEMA'],
            ['id' => 300,'departments_id'=>15,   'name'=>'SAN PABLO DE BORBUR'],
            ['id' => 301,'departments_id'=>15,   'name'=>'SANTANA'],
            ['id' => 302,'departments_id'=>15,   'name'=>'SANTA MARIA'],
            ['id' => 303,'departments_id'=>15,   'name'=>'SANTA ROSA DE VITERBO'],
            ['id' => 304,'departments_id'=>15,   'name'=>'SANTA SOFIA'],
            ['id' => 305,'departments_id'=>15,   'name'=>'SATIVANORTE'],
            ['id' => 306,'departments_id'=>15,   'name'=>'SATIVASUR'],
            ['id' => 307,'departments_id'=>15,   'name'=>'SIACHOQUE'],
            ['id' => 308,'departments_id'=>15,   'name'=>'SOATA'],
            ['id' => 309,'departments_id'=>15,   'name'=>'SOCOTA'],
            ['id' => 310,'departments_id'=>15,   'name'=>'SOCHA'],
            ['id' => 311,'departments_id'=>15,   'name'=>'SOGAMOSO'],
            ['id' => 312,'departments_id'=>15,   'name'=>'SOMONDOCO'],
            ['id' => 313,'departments_id'=>15,   'name'=>'SORA'],
            ['id' => 314,'departments_id'=>15,   'name'=>'SOTAQUIRA'],
            ['id' => 315,'departments_id'=>15,   'name'=>'SORACA'],
            ['id' => 316,'departments_id'=>15,   'name'=>'SUSACON'],
            ['id' => 317,'departments_id'=>15,   'name'=>'SUTAMARCHAN'],
            ['id' => 318,'departments_id'=>15,   'name'=>'SUTATENZA'],
            ['id' => 319,'departments_id'=>15,   'name'=>'TASCO'],
            ['id' => 320,'departments_id'=>15,   'name'=>'TENZA'],
            ['id' => 321,'departments_id'=>15,   'name'=>'TIBANA'],
            ['id' => 322,'departments_id'=>15,   'name'=>'TIBASOSA'],
            ['id' => 323,'departments_id'=>15,   'name'=>'TINJACA'],
            ['id' => 324,'departments_id'=>15,   'name'=>'TIPACOQUE'],
            ['id' => 325,'departments_id'=>15,   'name'=>'TOCA'],
            ['id' => 326,'departments_id'=>15,   'name'=>'TOGUI'],
            ['id' => 327,'departments_id'=>15,   'name'=>'TOPAGA'],
            ['id' => 328,'departments_id'=>15,   'name'=>'TOTA'],
            ['id' => 329,'departments_id'=>15,   'name'=>'TUNUNGUA'],
            ['id' => 330,'departments_id'=>15,   'name'=>'TURMEQUE'],
            ['id' => 331,'departments_id'=>15,   'name'=>'TUTA'],
            ['id' => 332,'departments_id'=>15,   'name'=>'TUTASA'],
            ['id' => 333,'departments_id'=>15,   'name'=>'UMBITA'],
            ['id' => 334,'departments_id'=>15,   'name'=>'VENTAQUEMADA'],
            ['id' => 335,'departments_id'=>15,   'name'=>'VIRACACHA'],
            ['id' => 336,'departments_id'=>15,   'name'=>'ZETAQUIRA'],
            ['id' => 337,'departments_id'=>17, 'name'=>'MANIZALES'],
            ['id' => 338,'departments_id'=>17,  'name'=>'AGUADAS'],
            ['id' => 339,'departments_id'=>17,  'name'=>'ANSERMA'],
            ['id' => 340,'departments_id'=>17,  'name'=>'ARANZAZU'],
            ['id' => 341,'departments_id'=>17,  'name'=>'BELALCAZAR'],
            ['id' => 342,'departments_id'=>17,   'name'=>'CHINCHINA'],
            ['id' => 343,'departments_id'=>17,   'name'=>'FILADELFIA'],
            ['id' => 344,'departments_id'=>17,   'name'=>'LA DORADA'],
            ['id' => 345,'departments_id'=>17,   'name'=>'LA MERCED'],
            ['id' => 346,'departments_id'=>17,   'name'=>'MANZANARES'],
            ['id' => 347,'departments_id'=>17,   'name'=>'MARMATO'],
            ['id' => 348,'departments_id'=>17,   'name'=>'MARQUETALIA'],
            ['id' => 349,'departments_id'=>17,   'name'=>'MARULANDA'],
            ['id' => 350,'departments_id'=>17,   'name'=>'NEIRA'],
            ['id' => 351,'departments_id'=>17,   'name'=>'NORCASIA'],
            ['id' => 352,'departments_id'=>17,   'name'=>'PACORA'],
            ['id' => 353,'departments_id'=>17,   'name'=>'PALESTINA'],
            ['id' => 354,'departments_id'=>17,   'name'=>'PENSILVANIA'],
            ['id' => 355,'departments_id'=>17,   'name'=>'RIOSUCIO'],
            ['id' => 356,'departments_id'=>17,   'name'=>'RISARALDA'],
            ['id' => 357,'departments_id'=>17,   'name'=>'SALAMINA'],
            ['id' => 358,'departments_id'=>17,   'name'=>'SAMANA'],
            ['id' => 359,'departments_id'=>17,   'name'=>'SAN JOSE'],
            ['id' => 360,'departments_id'=>17,   'name'=>'SUPIA'],
            ['id' => 361,'departments_id'=>17,   'name'=>'VICTORIA'],
            ['id' => 362,'departments_id'=>17,   'name'=>'VILLAMARIA'],
            ['id' => 363,'departments_id'=>17,   'name'=>'VITERBO'],
            ['id' => 364,'departments_id'=>18, 'name'=>'FLORENCIA'],
            ['id' => 365,'departments_id'=>18,  'name'=>'ALBANIA'],
            ['id' => 366,'departments_id'=>18,  'name'=>'BELEN DE LOS ANDAQUIES'],
            ['id' => 367,'departments_id'=>18,   'name'=>'CARTAGENA DEL CHAIRA'],
            ['id' => 368,'departments_id'=>18,   'name'=>'CURILLO'],
            ['id' => 369,'departments_id'=>18,   'name'=>'EL DONCELLO'],
            ['id' => 370,'departments_id'=>18,   'name'=>'EL PAUJIL'],
            ['id' => 371,'departments_id'=>18,   'name'=>'LA MONTANITA'],
            ['id' => 372,'departments_id'=>18,   'name'=>'MILAN'],
            ['id' => 373,'departments_id'=>18,   'name'=>'MORELIA'],
            ['id' => 374,'departments_id'=>18,   'name'=>'PUERTO RICO'],
            ['id' => 375,'departments_id'=>18,   'name'=>'SAN JOSE DE FRAGUA'],
            ['id' => 376,'departments_id'=>18,   'name'=>'SAN  VICENTE DEL CAGUAN'],
            ['id' => 377,'departments_id'=>18,   'name'=>'SOLANO'],
            ['id' => 378,'departments_id'=>18,   'name'=>'SOLITA'],
            ['id' => 379,'departments_id'=>18,   'name'=>'VALPARAISO'],
            ['id' => 380,'departments_id'=>19, 'name'=>'POPAYAN'],
            ['id' => 381,'departments_id'=>19,  'name'=>'ALMAGUER'],
            ['id' => 382,'departments_id'=>19,  'name'=>'ARGELIA'],
            ['id' => 383,'departments_id'=>19,  'name'=>'BALBOA'],
            ['id' => 384,'departments_id'=>19,   'name'=>'BOLIVAR'],
            ['id' => 385,'departments_id'=>19,   'name'=>'BUENOS AIRES'],
            ['id' => 386,'departments_id'=>19,   'name'=>'CAJIBIO'],
            ['id' => 387,'departments_id'=>19,   'name'=>'CALDONO'],
            ['id' => 388,'departments_id'=>19,   'name'=>'CALOTO'],
            ['id' => 389,'departments_id'=>19,   'name'=>'CORINTO'],
            ['id' => 390,'departments_id'=>19,   'name'=>'EL TAMBO'],
            ['id' => 391,'departments_id'=>19,   'name'=>'FLORENCIA'],
            ['id' => 392,'departments_id'=>19,   'name'=>'GUAPI'],
            ['id' => 393,'departments_id'=>19,   'name'=>'INZA'],
            ['id' => 394,'departments_id'=>19,   'name'=>'JAMBALO'],
            ['id' => 395,'departments_id'=>19,   'name'=>'LA SIERRA'],
            ['id' => 396,'departments_id'=>19,   'name'=>'LA VEGA'],
            ['id' => 397,'departments_id'=>19,   'name'=>'LOPEZ (MICAY)'],
            ['id' => 398,'departments_id'=>19,   'name'=>'MERCADERES'],
            ['id' => 399,'departments_id'=>19,   'name'=>'MIRANDA'],
            ['id' => 400,'departments_id'=>19,   'name'=>'MORALES'],
            ['id' => 401,'departments_id'=>19,   'name'=>'PADILLA'],
            ['id' => 402,'departments_id'=>19,   'name'=>'PAEZ (BELALCAZAR)'],
            ['id' => 403,'departments_id'=>19,   'name'=>'PATIA (EL BORDO)'],
            ['id' => 404,'departments_id'=>19,   'name'=>'PIAMONTE'],
            ['id' => 405,'departments_id'=>19,   'name'=>'PIENDAMO'],
            ['id' => 406,'departments_id'=>19,   'name'=>'PUERTO TEJADA'],
            ['id' => 407,'departments_id'=>19,   'name'=>'PURACE (COCONUCO)'],
            ['id' => 408,'departments_id'=>19,   'name'=>'ROSAS'],
            ['id' => 409,'departments_id'=>19,   'name'=>'SAN SEBASTIAN'],
            ['id' => 410,'departments_id'=>19,   'name'=>'SANTANDER DE QUILICHAO'],
            ['id' => 411,'departments_id'=>19,   'name'=>'SANTA ROSA'],
            ['id' => 412,'departments_id'=>19,   'name'=>'SILVIA'],
            ['id' => 413,'departments_id'=>19,   'name'=>'SOTARA (PAISPAMBA)'],
            ['id' => 414,'departments_id'=>19,   'name'=>'SUAREZ'],
            ['id' => 415,'departments_id'=>19,   'name'=>'TIMBIO'],
            ['id' => 416,'departments_id'=>19,   'name'=>'TIMBIQUI'],
            ['id' => 417,'departments_id'=>19,   'name'=>'TORIBIO'],
            ['id' => 418,'departments_id'=>19,   'name'=>'TOTORO'],
            ['id' => 419,'departments_id'=>19,   'name'=>'VILLARICA'],
            ['id' => 420,'departments_id'=>20, 'name'=>'VALLEDUPAR'],
            ['id' => 421,'departments_id'=>20,  'name'=>'AGUACHICA'],
            ['id' => 422,'departments_id'=>20,  'name'=>'AGUSTIN CODAZZI'],
            ['id' => 423,'departments_id'=>20,  'name'=>'ASTREA'],
            ['id' => 424,'departments_id'=>20,  'name'=>'BECERRIL'],
            ['id' => 425,'departments_id'=>20,  'name'=>'BOSCONIA'],
            ['id' => 426,'departments_id'=>20,   'name'=>'CHIMICHAGUA'],
            ['id' => 427,'departments_id'=>20,   'name'=>'CHIRIGUANA'	]	,
            ['id' => 428,'departments_id'=>20,   'name'=>'CURUMANI'],
            ['id' => 429,'departments_id'=>20,   'name'=>'EL COPEY'],
            ['id' => 430,'departments_id'=>20,   'name'=>'EL PASO'],
            ['id' => 431,'departments_id'=>20,   'name'=>'GAMARRA'],
            ['id' => 432,'departments_id'=>20,   'name'=>'GONZALEZ'],
            ['id' => 433,'departments_id'=>20,   'name'=>'LA GLORIA'],
            ['id' => 434,'departments_id'=>20,   'name'=>'LA JAGUA IBIRICO'],
            ['id' => 435,'departments_id'=>20,   'name'=>'MANAURE (BALCON DEL CESAR'],
            ['id' => 436,'departments_id'=>20,   'name'=>'PAILITAS'],
            ['id' => 437,'departments_id'=>20,   'name'=>'PELAYA'],
            ['id' => 438,'departments_id'=>20,   'name'=>'PUEBLO BELLO'],
            ['id' => 439,'departments_id'=>20,   'name'=>'RIO DE ORO'],
            ['id' => 440,'departments_id'=>20,   'name'=>'LA PAZ (ROBLES)'],
            ['id' => 441,'departments_id'=>20,   'name'=>'SAN ALBERTO'],
            ['id' => 442,'departments_id'=>20,   'name'=>'SAN DIEGO'],
            ['id' => 443,'departments_id'=>20,   'name'=>'SAN MARTIN'],
            ['id' => 444,'departments_id'=>20,   'name'=>'TAMALAMEQUE'],
            ['id' => 445,'departments_id'=>23, 'name'=>'MONTERIA'],
            ['id' => 446,'departments_id'=>23,  'name'=>'AYAPEL'],
            ['id' => 447,'departments_id'=>23,  'name'=>'BUENAVISTA'],
            ['id' => 448,'departments_id'=>23,  'name'=>'CANALETE'],
            ['id' => 449,'departments_id'=>23,   'name'=>'CERETE'],
            ['id' => 450,'departments_id'=>23,   'name'=>'CHIMA'],
            ['id' => 451,'departments_id'=>23,   'name'=>'CHINU'],
            ['id' => 452,'departments_id'=>23,   'name'=>'CIENAGA DE ORO'],
            ['id' => 453,'departments_id'=>23,   'name'=>'COTORRA'],
            ['id' => 454,'departments_id'=>23,   'name'=>'LA APARTADA'],
            ['id' => 455,'departments_id'=>23,   'name'=>'LORICA'],
            ['id' => 456,'departments_id'=>23,   'name'=>'LOS CORDOBAS'],
            ['id' => 457,'departments_id'=>23,   'name'=>'MOMIL'],
            ['id' => 458,'departments_id'=>23,   'name'=>'MONTELIBANO'],
            ['id' => 459,'departments_id'=>23,   'name'=>'MONITOS'],
            ['id' => 460,'departments_id'=>23,   'name'=>'PLANETA RICA'],
            ['id' => 461,'departments_id'=>23,   'name'=>'PUEBLO NUEVO'],
            ['id' => 462,'departments_id'=>23,   'name'=>'PUERTO ESCONDIDO'],
            ['id' => 463,'departments_id'=>23,   'name'=>'PUERTO LIBERTADOR'],
            ['id' => 464,'departments_id'=>23,   'name'=>'PURISIMA'],
            ['id' => 465,'departments_id'=>23,   'name'=>'SAHAGUN'],
            ['id' => 466,'departments_id'=>23,   'name'=>'SAN ANDRES SOTAVENTO'],
            ['id' => 467,'departments_id'=>23,   'name'=>'SAN ANTERO'],
            ['id' => 468,'departments_id'=>23,   'name'=>'SAN BERNARDO DEL VIENTO'],
            ['id' => 469,'departments_id'=>23,   'name'=>'SAN CARLOS'],
            ['id' => 470,'departments_id'=>23,   'name'=>'SAN PELAYO'],
            ['id' => 471,'departments_id'=>23,   'name'=>'TIERRALTA'],
            ['id' => 472,'departments_id'=>23,   'name'=>'VALENCIA'],
            ['id' => 473,'departments_id'=>25, 'name'=>'AGUA DE DIOS'],
            ['id' => 474,'departments_id'=>25,  'name'=>'ALBAN'],
            ['id' => 475,'departments_id'=>25,  'name'=>'ANAPOIMA'],
            ['id' => 476,'departments_id'=>25,  'name'=>'ANOLAIMA'],
            ['id' => 477,'departments_id'=>25,  'name'=>'ARBELAEZ'],
            ['id' => 478,'departments_id'=>25,  'name'=>'BELTRAN'],
            ['id' => 479,'departments_id'=>25,  'name'=>'BITUIMA'],
            ['id' => 480,'departments_id'=>25,  'name'=>'BOJACA'],
            ['id' => 481,'departments_id'=>25,   'name'=>'CABRERA'],
            ['id' => 482,'departments_id'=>25,   'name'=>'CACHIPAY'],
            ['id' => 483,'departments_id'=>25,   'name'=>'CAJICA'],
            ['id' => 484,'departments_id'=>25,   'name'=>'CAPARRAPI'],
            ['id' => 485,'departments_id'=>25,   'name'=>'CAQUEZA'],
            ['id' => 486,'departments_id'=>25,   'name'=>'CARMEN DE CARUPA'],
            ['id' => 487,'departments_id'=>25,   'name'=>'CHAGUANI'],
            ['id' => 488,'departments_id'=>25,   'name'=>'CHIA'],
            ['id' => 489,'departments_id'=>25,   'name'=>'CHIPAQUE'],
            ['id' => 490,'departments_id'=>25,   'name'=>'CHOACHI'],
            ['id' => 491,'departments_id'=>25,   'name'=>'CHOCONTA'],
            ['id' => 492,'departments_id'=>25,   'name'=>'COGUA'],
            ['id' => 493,'departments_id'=>25,   'name'=>'COTA'],
            ['id' => 494,'departments_id'=>25,   'name'=>'CUCUNUBA'],
            ['id' => 495,'departments_id'=>25,   'name'=>'EL COLEGIO'],
            ['id' => 496,'departments_id'=>25,   'name'=>'EL PENON'],
            ['id' => 497,'departments_id'=>25,   'name'=>'EL ROSAL'],
            ['id' => 498,'departments_id'=>25,   'name'=>'FACATATIVA'],
            ['id' => 499,'departments_id'=>25,   'name'=>'FOMEQUE'],
            ['id' => 500,'departments_id'=>25,   'name'=>'FOSCA'],
            ['id' => 501,'departments_id'=>25,   'name'=>'FUNZA'],
            ['id' => 502,'departments_id'=>25,   'name'=>'FUQUENE'],
            ['id' => 503,'departments_id'=>25,   'name'=>'FUSAGASUGA'],
            ['id' => 504,'departments_id'=>25,   'name'=>'GACHALA'],
            ['id' => 505,'departments_id'=>25,   'name'=>'GACHANCIPA'],
            ['id' => 506,'departments_id'=>25,   'name'=>'GACHETA'],
            ['id' => 507,'departments_id'=>25,   'name'=>'GAMA'],
            ['id' => 508,'departments_id'=>25,   'name'=>'GIRARDOT'],
            ['id' => 509,'departments_id'=>25,   'name'=>'GRANADA'],
            ['id' => 510,'departments_id'=>25,   'name'=>'GUACHETA'],
            ['id' => 511,'departments_id'=>25,   'name'=>'GUADUAS'],
            ['id' => 512,'departments_id'=>25,   'name'=>'GUASCA'],
            ['id' => 513,'departments_id'=>25,   'name'=>'GUATAQUI'],
            ['id' => 514,'departments_id'=>25,   'name'=>'GUATAVITA'],
            ['id' => 515,'departments_id'=>25,   'name'=>'GUAYABAL DE SIQUIMA'],
            ['id' => 516,'departments_id'=>25,   'name'=>'GUAYABETAL'],
            ['id' => 517,'departments_id'=>25,   'name'=>'GUTIERREZ'],
            ['id' => 518,'departments_id'=>25,   'name'=>'JERUSALEN'],
            ['id' => 519,'departments_id'=>25,   'name'=>'JUNIN'],
            ['id' => 520,'departments_id'=>25,   'name'=>'LA CALERA'],
            ['id' => 521,'departments_id'=>25,   'name'=>'LA MESA'],
            ['id' => 522,'departments_id'=>25,   'name'=>'LA PALMA'],
            ['id' => 523,'departments_id'=>25,   'name'=>'LA PENA'],
            ['id' => 524,'departments_id'=>25,   'name'=>'LA VEGA'],
            ['id' => 525,'departments_id'=>25,   'name'=>'LENGUAZAQUE'],
            ['id' => 526,'departments_id'=>25,   'name'=>'MACHETA'],
            ['id' => 527,'departments_id'=>25,   'name'=>'MADRID'],
            ['id' => 528,'departments_id'=>25,   'name'=>'MANTA'],
            ['id' => 529,'departments_id'=>25,   'name'=>'MEDINA'],
            ['id' => 530,'departments_id'=>25,   'name'=>'MOSQUERA'],
            ['id' => 531,'departments_id'=>25,   'name'=>'NARINO'],
            ['id' => 532,'departments_id'=>25,   'name'=>'NEMOCON'],
            ['id' => 533,'departments_id'=>25,   'name'=>'NILO'],
            ['id' => 534,'departments_id'=>25,   'name'=>'NIMAIMA'],
            ['id' => 535,'departments_id'=>25,   'name'=>'NOCAIMA'],
            ['id' => 536,'departments_id'=>25,   'name'=>'VENECIA (OSPINA PEREZ)'],
            ['id' => 537,'departments_id'=>25,   'name'=>'PACHO'],
            ['id' => 538,'departments_id'=>25,   'name'=>'PAIME'],
            ['id' => 539,'departments_id'=>25,   'name'=>'PANDI'],
            ['id' => 540,'departments_id'=>25,   'name'=>'PARATEBUENO'],
            ['id' => 541,'departments_id'=>25,   'name'=>'PASCA'],
            ['id' => 542,'departments_id'=>25,   'name'=>'PUERTO SALGAR'],
            ['id' => 543,'departments_id'=>25,   'name'=>'PULI'],
            ['id' => 544,'departments_id'=>25,   'name'=>'QUEBRADANEGRA'],
            ['id' => 545,'departments_id'=>25,   'name'=>'QUETAME'],
            ['id' => 546,'departments_id'=>25,   'name'=>'QUIPILE'],
            ['id' => 547,'departments_id'=>25,   'name'=>'APULO (RAFAEL REYES)'],
            ['id' => 548,'departments_id'=>25,   'name'=>'RICAURTE'],
            ['id' => 549,'departments_id'=>25,   'name'=>'SAN  ANTONIO DEL  TEQUEND'],
            ['id' => 550,'departments_id'=>25,   'name'=>'SAN BERNARDO'],
            ['id' => 551,'departments_id'=>25,   'name'=>'SAN CAYETANO'],
            ['id' => 552,'departments_id'=>25,   'name'=>'SAN FRANCISCO'],
            ['id' => 553,'departments_id'=>25,   'name'=>'SAN JUAN DE RIOSECO'],
            ['id' => 554,'departments_id'=>25,   'name'=>'SASAIMA'],
            ['id' => 555,'departments_id'=>25,   'name'=>'SESQUILE'],
            ['id' => 556,'departments_id'=>25,   'name'=>'SIBATE'],
            ['id' => 557,'departments_id'=>25,   'name'=>'SILVANIA'],
            ['id' => 558,'departments_id'=>25,   'name'=>'SIMIJACA'],
            ['id' => 559,'departments_id'=>25,   'name'=>'SOACHA'],
            ['id' => 560,'departments_id'=>25,   'name'=>'SOPO'],
            ['id' => 561,'departments_id'=>25,   'name'=>'SUBACHOQUE'],
            ['id' => 562,'departments_id'=>25,   'name'=>'SUESCA'],
            ['id' => 563,'departments_id'=>25,   'name'=>'SUPATA'],
            ['id' => 564,'departments_id'=>25,   'name'=>'SUSA'],
            ['id' => 565,'departments_id'=>25,   'name'=>'SUTATAUSA'],
            ['id' => 566,'departments_id'=>25,   'name'=>'TABIO'],
            ['id' => 567,'departments_id'=>25,   'name'=>'TAUSA'],
            ['id' => 568,'departments_id'=>25,   'name'=>'TENA'],
            ['id' => 569,'departments_id'=>25,   'name'=>'TENJO'],
            ['id' => 570,'departments_id'=>25,   'name'=>'TIBACUY'],
            ['id' => 571,'departments_id'=>25,   'name'=>'TIBIRITA'],
            ['id' => 572,'departments_id'=>25,   'name'=>'TOCAIMA'],
            ['id' => 573,'departments_id'=>25,   'name'=>'TOCANCIPA'],
            ['id' => 574,'departments_id'=>25,   'name'=>'TOPAIPI'],
            ['id' => 575,'departments_id'=>25,   'name'=>'UBALA'],
            ['id' => 576,'departments_id'=>25,   'name'=>'UBAQUE'],
            ['id' => 577,'departments_id'=>25,   'name'=>'UBATE'],
            ['id' => 578,'departments_id'=>25,   'name'=>'UNE'],
            ['id' => 579,'departments_id'=>25,   'name'=>'UTICA'],
            ['id' => 580,'departments_id'=>25,   'name'=>'VERGARA'],
            ['id' => 581,'departments_id'=>25,   'name'=>'VIANI'],
            ['id' => 582,'departments_id'=>25,   'name'=>'VILLAGOMEZ'],
            ['id' => 583,'departments_id'=>25,   'name'=>'VILLAPINZON'],
            ['id' => 584,'departments_id'=>25,   'name'=>'VILLETA'],
            ['id' => 585,'departments_id'=>25,   'name'=>'VIOTA'],
            ['id' => 586,'departments_id'=>25,   'name'=>'YACOPI'],
            ['id' => 587,'departments_id'=>25,   'name'=>'ZIPACON'],
            ['id' => 588,'departments_id'=>25,   'name'=>'ZIPAQUIRA'],
            ['id' => 589,'departments_id'=>27, 'name'=>'QUIBDO (SAN FRANCISCO DE'],
            ['id' => 590,'departments_id'=>27, 'name'=>'ACANDI'],
            ['id' => 591,'departments_id'=>27,  'name'=>'ALTO BAUDO (PIE DE PATO)'],
            ['id' => 592,'departments_id'=>27,  'name'=>'ATRATO'],
            ['id' => 593,'departments_id'=>27,  'name'=>'BAGADO'],
            ['id' => 594,'departments_id'=>27,  'name'=>'BAHIA SOLANO (MUTIS)'],
            ['id' => 595,'departments_id'=>27,  'name'=>'BAJO BAUDO (PIZARRO)'],
            ['id' => 596,'departments_id'=>27,  'name'=>'BOJAYA (BELLAVISTA)'],
            ['id' => 597,'departments_id'=>27,   'name'=>'CANTON DE SAN PABLO (MANA'],
            ['id' => 598,'departments_id'=>27,   'name'=>'CONDOTO'],
            ['id' => 599,'departments_id'=>27,   'name'=>'EL CARMEN DE ATRATO'],
            ['id' => 600,'departments_id'=>27,   'name'=>'LITORAL DEL BAJO SAN JUAN'],
            ['id' => 601,'departments_id'=>27,   'name'=>'ISTMINA'],
            ['id' => 602,'departments_id'=>27,   'name'=>'JURADO'],
            ['id' => 603,'departments_id'=>27,   'name'=>'LLORO'],
            ['id' => 604,'departments_id'=>27,   'name'=>'MEDIO ATRATO'],
            ['id' => 605,'departments_id'=>27,   'name'=>'MEDIO BAUDO'],
            ['id' => 606,'departments_id'=>27,   'name'=>'NOVITA'],
            ['id' => 607,'departments_id'=>27,   'name'=>'NUQUI'],
            ['id' => 608,'departments_id'=>27,   'name'=>'RIOQUITO'],
            ['id' => 609,'departments_id'=>27,   'name'=>'RIOSUCIO'],
            ['id' => 610,'departments_id'=>27,   'name'=>'SAN JOSE DEL PALMAR'],
            ['id' => 611,'departments_id'=>27,   'name'=>'SIPI'],
            ['id' => 612,'departments_id'=>27,   'name'=>'TADO'],
            ['id' => 613,'departments_id'=>27,   'name'=>'UNGUIA'],
            ['id' => 614,'departments_id'=>27,   'name'=>'UNION PANAMERICANA'],
            ['id' => 615,'departments_id'=>41, 'name'=>'NEIVA'],
            ['id' => 616,'departments_id'=>41, 'name'=>'ACEVEDO'],
            ['id' => 617,'departments_id'=>41,  'name'=>'AGRADO'],
            ['id' => 618,'departments_id'=>41,  'name'=>'AIPE'],
            ['id' => 619,'departments_id'=>41,  'name'=>'ALGECIRAS'],
            ['id' => 620,'departments_id'=>41,  'name'=>'ALTAMIRA'],
            ['id' => 621,'departments_id'=>41,  'name'=>'BARAYA'],
            ['id' => 622,'departments_id'=>41,   'name'=>'CAMPOALEGRE'],
            ['id' => 623,'departments_id'=>41,   'name'=>'COLOMBIA'],
            ['id' => 624,'departments_id'=>41,   'name'=>'ELIAS'],
            ['id' => 625,'departments_id'=>41,   'name'=>'GARZON'],
            ['id' => 626,'departments_id'=>41,   'name'=>'GIGANTE'],
            ['id' => 627,'departments_id'=>41,   'name'=>'GUADALUPE'],
            ['id' => 628,'departments_id'=>41,   'name'=>'HOBO'],
            ['id' => 629,'departments_id'=>41,   'name'=>'IQUIRA'],
            ['id' => 630,'departments_id'=>41,   'name'=>'ISNOS (SAN JOSE DE ISNOS)'],
            ['id' => 631,'departments_id'=>41,   'name'=>'LA ARGENTINA'],
            ['id' => 632,'departments_id'=>41,   'name'=>'LA PLATA'],
            ['id' => 633,'departments_id'=>41,   'name'=>'NATAGA'],
            ['id' => 634,'departments_id'=>41,   'name'=>'OPORAPA'],
            ['id' => 635,'departments_id'=>41,   'name'=>'PAICOL'],
            ['id' => 636,'departments_id'=>41,   'name'=>'PALERMO'],
            ['id' => 637,'departments_id'=>41,   'name'=>'PALESTINA'],
            ['id' => 638,'departments_id'=>41,   'name'=>'PITAL'],
            ['id' => 639,'departments_id'=>41,   'name'=>'PITALITO'],
            ['id' => 640,'departments_id'=>41,   'name'=>'RIVERA'],
            ['id' => 641,'departments_id'=>41,   'name'=>'SALADOBLANCO'],
            ['id' => 642,'departments_id'=>41,   'name'=>'SAN AGUSTIN'],
            ['id' => 643,'departments_id'=>41,   'name'=>'SANTA MARIA'],
            ['id' => 644,'departments_id'=>41,   'name'=>'SUAZA'],
            ['id' => 645,'departments_id'=>41,   'name'=>'TARQUI'],
            ['id' => 646,'departments_id'=>41,   'name'=>'TESALIA'],
            ['id' => 647,'departments_id'=>41,   'name'=>'TELLO'],
            ['id' => 648,'departments_id'=>41,   'name'=>'TERUEL'],
            ['id' => 649,'departments_id'=>41,   'name'=>'TIMANA'],
            ['id' => 650,'departments_id'=>41,   'name'=>'VILLAVIEJA'],
            ['id' => 651,'departments_id'=>41,   'name'=>'YAGUARA'],
            ['id' => 652,'departments_id'=>44, 'name'=>'RIOHACHA'],
            ['id' => 653,'departments_id'=>44,  'name'=>'BARRANCAS'],
            ['id' => 654,'departments_id'=>44,  'name'=>'DIBULLA'],
            ['id' => 655,'departments_id'=>44,  'name'=>'DISTRACCION'],
            ['id' => 656,'departments_id'=>44,   'name'=>'EL MOLINO'],
            ['id' => 657,'departments_id'=>44,   'name'=>'FONSECA'],
            ['id' => 658,'departments_id'=>44,   'name'=>'HATONUEVO'],
            ['id' => 659,'departments_id'=>44,   'name'=>'LA JAGUA DEL PILAR'],
            ['id' => 660,'departments_id'=>44,   'name'=>'MAICAO'],
            ['id' => 661,'departments_id'=>44,   'name'=>'MANAURE'],
            ['id' => 662,'departments_id'=>44,   'name'=>'SAN JUAN DEL CESAR'],
            ['id' => 663,'departments_id'=>44,   'name'=>'URIBIA'],
            ['id' => 664,'departments_id'=>44,   'name'=>'URUMITA'],
            ['id' => 665,'departments_id'=>44,   'name'=>'VILLANUEVA'],
            ['id' => 666,'departments_id'=>47, 'name'=>'SANTA MARTA (DISTRITO TUR'],
            ['id' => 667,'departments_id'=>47,  'name'=>'ALGARROBO'],
            ['id' => 668,'departments_id'=>47,  'name'=>'ARACATACA'],
            ['id' => 669,'departments_id'=>47,  'name'=>'ARIGUANI (EL DIFICIL)'],
            ['id' => 670,'departments_id'=>47,   'name'=>'CERRO SAN ANTONIO'],
            ['id' => 671,'departments_id'=>47,   'name'=>'CHIVOLO'],
            ['id' => 672,'departments_id'=>47,   'name'=>'CIENAGA'],
            ['id' => 673,'departments_id'=>47,   'name'=>'CONCORDIA'],
            ['id' => 674,'departments_id'=>47,   'name'=>'EL BANCO'],
            ['id' => 675,'departments_id'=>47,   'name'=>'EL PINON'],
            ['id' => 676,'departments_id'=>47,   'name'=>'EL RETEN'],
            ['id' => 677,'departments_id'=>47,   'name'=>'FUNDACION'],
            ['id' => 678,'departments_id'=>47,   'name'=>'GUAMAL'],
            ['id' => 679,'departments_id'=>47,   'name'=>'PEDRAZA'],
            ['id' => 680,'departments_id'=>47,   'name'=>'PIJINO DEL CARMEN (PIJINO'],
            ['id' => 681,'departments_id'=>47,   'name'=>'PIVIJAY'],
            ['id' => 682,'departments_id'=>47,   'name'=>'PLATO'],
            ['id' => 683,'departments_id'=>47,   'name'=>'PUEBLOVIEJO'],
            ['id' => 684,'departments_id'=>47,   'name'=>'REMOLINO'],
            ['id' => 685,'departments_id'=>47,   'name'=>'SABANAS DE SAN ANGEL'],
            ['id' => 686,'departments_id'=>47,   'name'=>'SALAMINA'],
            ['id' => 687,'departments_id'=>47,   'name'=>'SAN SEBASTIAN DE BUENAVIS'],
            ['id' => 688,'departments_id'=>47,   'name'=>'SAN ZENON'],
            ['id' => 689,'departments_id'=>47,   'name'=>'SANTA ANA'],
            ['id' => 690,'departments_id'=>47,   'name'=>'SITIONUEVO'],
            ['id' => 691,'departments_id'=>47,   'name'=>'TENERIFE'],
            ['id' => 692,'departments_id'=>50, 'name'=>'VILLAVICENCIO'],
            ['id' => 693,'departments_id'=>50, 'name'=>'ACACIAS'],
            ['id' => 694,'departments_id'=>50,   'name'=>'BARRANCA DE UPIA'],
            ['id' => 695,'departments_id'=>50,   'name'=>'CABUYARO'],
            ['id' => 696,'departments_id'=>50,   'name'=>'CASTILLA LA NUEVA'],
            ['id' => 697,'departments_id'=>50,   'name'=>'SAN LUIS DE CUBARRAL'],
            ['id' => 698,'departments_id'=>50,   'name'=>'CUMARAL'],
            ['id' => 699,'departments_id'=>50,   'name'=>'EL CALVARIO'],
            ['id' => 700,'departments_id'=>50,   'name'=>'EL CASTILLO'],
            ['id' => 701,'departments_id'=>50,   'name'=>'EL DORADO'],
            ['id' => 702,'departments_id'=>50,   'name'=>'FUENTE DE ORO'],
            ['id' => 703,'departments_id'=>50,   'name'=>'GRANADA'],
            ['id' => 704,'departments_id'=>50,   'name'=>'GUAMAL'],
            ['id' => 705,'departments_id'=>50,   'name'=>'MAPIRIPAN'],
            ['id' => 706,'departments_id'=>50,   'name'=>'MESETAS'],
            ['id' => 707,'departments_id'=>50,   'name'=>'LA MACARENA'],
            ['id' => 708,'departments_id'=>50,   'name'=>'LA URIBE'],
            ['id' => 709,'departments_id'=>50,   'name'=>'LEJANIAS'],
            ['id' => 710,'departments_id'=>50,   'name'=>'PUERTO CONCORDIA'],
            ['id' => 711,'departments_id'=>50,   'name'=>'PUERTO GAITAN'],
            ['id' => 712,'departments_id'=>50,   'name'=>'PUERTO LOPEZ'],
            ['id' => 713,'departments_id'=>50,   'name'=>'PUERTO LLERAS'],
            ['id' => 714,'departments_id'=>50,   'name'=>'PUERTO RICO'],
            ['id' => 715,'departments_id'=>50,   'name'=>'RESTREPO'],
            ['id' => 716,'departments_id'=>50,   'name'=>'SAN CARLOS DE GUAROA'],
            ['id' => 717,'departments_id'=>50,   'name'=>'SAN  JUAN DE ARAMA'],
            ['id' => 718,'departments_id'=>50,   'name'=>'SAN JUANITO'],
            ['id' => 719,'departments_id'=>50,   'name'=>'SAN MARTIN'],
            ['id' => 720,'departments_id'=>50,   'name'=>'VISTAHERMOSA'],
            ['id' => 721,'departments_id'=>52, 'name'=>'PASTO (SAN JUAN DE PASTO)'],
            ['id' => 722,'departments_id'=>52,  'name'=>'ALBAN (SAN JOSE)'],
            ['id' => 723,'departments_id'=>52,  'name'=>'ALDANA'],
            ['id' => 724,'departments_id'=>52,  'name'=>'ANCUYA'],
            ['id' => 725,'departments_id'=>52,  'name'=>'ARBOLEDA (BERRUECOS)'],
            ['id' => 726,'departments_id'=>52,  'name'=>'BARBACOAS'],
            ['id' => 727,'departments_id'=>52,  'name'=>'BELEN'],
            ['id' => 728,'departments_id'=>52,   'name'=>'BUESACO'],
            ['id' => 729,'departments_id'=>52,   'name'=>'COLON (GENOVA)'],
            ['id' => 730,'departments_id'=>52,   'name'=>'CONSACA'],
            ['id' => 731,'departments_id'=>52,   'name'=>'CONTADERO'],
            ['id' => 732,'departments_id'=>52,   'name'=>'CORDOBA'],
            ['id' => 733,'departments_id'=>52,   'name'=>'CUASPUD (CARLOSAMA)'],
            ['id' => 734,'departments_id'=>52,   'name'=>'CUMBAL'],
            ['id' => 735,'departments_id'=>52,   'name'=>'CUMBITARA'],
            ['id' => 736,'departments_id'=>52,   'name'=>'CHACHAGUI'],
            ['id' => 737,'departments_id'=>52,   'name'=>'EL CHARCO'],
            ['id' => 738,'departments_id'=>52,   'name'=>'EL PENOL'],
            ['id' => 739,'departments_id'=>52,   'name'=>'EL ROSARIO'],
            ['id' => 740,'departments_id'=>52,   'name'=>'EL TABLON'],
            ['id' => 741,'departments_id'=>52,   'name'=>'EL TAMBO'],
            ['id' => 742,'departments_id'=>52,   'name'=>'FUNES'],
            ['id' => 743,'departments_id'=>52,   'name'=>'GUACHUCAL'],
            ['id' => 744,'departments_id'=>52,   'name'=>'GUAITARILLA'],
            ['id' => 745,'departments_id'=>52,   'name'=>'GUALMATAN'],
            ['id' => 746,'departments_id'=>52,   'name'=>'ILES'],
            ['id' => 747,'departments_id'=>52,   'name'=>'IMUES'],
            ['id' => 748,'departments_id'=>52,   'name'=>'IPIALES'],
            ['id' => 749,'departments_id'=>52,   'name'=>'LA CRUZ'],
            ['id' => 750,'departments_id'=>52,   'name'=>'LA FLORIDA'],
            ['id' => 751,'departments_id'=>52,   'name'=>'LA LLANADA'],
            ['id' => 752,'departments_id'=>52,   'name'=>'LA TOLA'],
            ['id' => 753,'departments_id'=>52,   'name'=>'LA UNION'],
            ['id' => 754,'departments_id'=>52,   'name'=>'LEIVA'],
            ['id' => 755,'departments_id'=>52,   'name'=>'LINARES'],
            ['id' => 756,'departments_id'=>52,   'name'=>'LOS ANDES (SOTOMAYOR)'],
            ['id' => 757,'departments_id'=>52,   'name'=>'MAGUI (PAYAN)'],
            ['id' => 758,'departments_id'=>52,   'name'=>'MALLAMA (PIEDRANCHA)'],
            ['id' => 759,'departments_id'=>52,   'name'=>'MOSQUERA'],
            ['id' => 760,'departments_id'=>52,   'name'=>'OLAYA HERRERA (BOCAS DE S'],
            ['id' => 761,'departments_id'=>52,   'name'=>'OSPINA'],
            ['id' => 762,'departments_id'=>52,   'name'=>'FRANCISCO PIZARRO (SALAHO'],
            ['id' => 763,'departments_id'=>52,   'name'=>'POLICARPA'],
            ['id' => 764,'departments_id'=>52,   'name'=>'POTOSI'],
            ['id' => 765,'departments_id'=>52,   'name'=>'PROVIDENCIA'],
            ['id' => 766,'departments_id'=>52,   'name'=>'PUERRES'],
            ['id' => 767,'departments_id'=>52,   'name'=>'PUPIALES'],
            ['id' => 768,'departments_id'=>52,   'name'=>'RICAURTE'],
            ['id' => 769,'departments_id'=>52,   'name'=>'ROBERTO PAYAN (SAN JOSE)'],
            ['id' => 770,'departments_id'=>52,   'name'=>'SAMANIEGO'],
            ['id' => 771,'departments_id'=>52,   'name'=>'SANDONA'],
            ['id' => 772,'departments_id'=>52,   'name'=>'SAN BERNARDO'],
            ['id' => 773,'departments_id'=>52,   'name'=>'SAN LORENZO'],
            ['id' => 774,'departments_id'=>52,   'name'=>'SAN PABLO'],
            ['id' => 775,'departments_id'=>52,   'name'=>'SAN PEDRO DE CARTAGO'],
            ['id' => 776,'departments_id'=>52,   'name'=>'SANTA BARBARA (ISCUANDE)'],
            ['id' => 777,'departments_id'=>52,   'name'=>'SANTA CRUZ (GUACHAVES)'],
            ['id' => 778,'departments_id'=>52,   'name'=>'SAPUYES'],
            ['id' => 779,'departments_id'=>52,   'name'=>'TAMINANGO'],
            ['id' => 780,'departments_id'=>52,   'name'=>'TANGUA'],
            ['id' => 781,'departments_id'=>52,   'name'=>'TUMACO'],
            ['id' => 782,'departments_id'=>52,   'name'=>'TUQUERRES'],
            ['id' => 783,'departments_id'=>52,   'name'=>'YACUANQUER'],
            ['id' => 784,'departments_id'=>54, 'name'=>'CUCUTA'],
            ['id' => 785,'departments_id'=>54, 'name'=>'ABREGO'],
            ['id' => 786,'departments_id'=>54,  'name'=>'ARBOLEDAS'],
            ['id' => 787,'departments_id'=>54,  'name'=>'BOCHALEMA'],
            ['id' => 788,'departments_id'=>54,   'name'=>'BUCARASICA'],
            ['id' => 789,'departments_id'=>54,   'name'=>'CACOTA'],
            ['id' => 790,'departments_id'=>54,   'name'=>'CACHIRA'],
            ['id' => 791,'departments_id'=>54,   'name'=>'CHINACOTA'],
            ['id' => 792,'departments_id'=>54,   'name'=>'CHITAGA'],
            ['id' => 793,'departments_id'=>54,   'name'=>'CONVENCION'],
            ['id' => 794,'departments_id'=>54,   'name'=>'CUCUTILLA'],
            ['id' => 795,'departments_id'=>54,   'name'=>'DURANIA'],
            ['id' => 796,'departments_id'=>54,   'name'=>'EL CARMEN'],
            ['id' => 797,'departments_id'=>54,   'name'=>'EL TARRA'],
            ['id' => 798,'departments_id'=>54,   'name'=>'EL ZULIA'],
            ['id' => 799,'departments_id'=>54,   'name'=>'GRAMALOTE'],
            ['id' => 800,'departments_id'=>54,   'name'=>'HACARI'],
            ['id' => 801,'departments_id'=>54,   'name'=>'HERRAN'],
            ['id' => 802,'departments_id'=>54,   'name'=>'LABATECA'],
            ['id' => 803,'departments_id'=>54,   'name'=>'LA ESPERANZA'],
            ['id' => 804,'departments_id'=>54,   'name'=>'LA PLAYA'],
            ['id' => 805,'departments_id'=>54,   'name'=>'LOS PATIOS'],
            ['id' => 806,'departments_id'=>54,   'name'=>'LOURDES'],
            ['id' => 807,'departments_id'=>54,   'name'=>'MUTISCUA'],
            ['id' => 808,'departments_id'=>54,   'name'=>'OCANA'],
            ['id' => 809,'departments_id'=>54,   'name'=>'PAMPLONA'],
            ['id' => 810,'departments_id'=>54,   'name'=>'PAMPLONITA'],
            ['id' => 811,'departments_id'=>54,   'name'=>'PUERTO SANTANDER'],
            ['id' => 812,'departments_id'=>54,   'name'=>'RAGONVALIA'],
            ['id' => 813,'departments_id'=>54,   'name'=>'SALAZAR'],
            ['id' => 814,'departments_id'=>54,   'name'=>'SAN CALIXTO'],
            ['id' => 815,'departments_id'=>54,   'name'=>'SAN CAYETANO'],
            ['id' => 816,'departments_id'=>54,   'name'=>'SANTIAGO'],
            ['id' => 817,'departments_id'=>54,   'name'=>'SARDINATA'],
            ['id' => 818,'departments_id'=>54,   'name'=>'SILOS'],
            ['id' => 819,'departments_id'=>54,   'name'=>'TEORAMA'],
            ['id' => 820,'departments_id'=>54,   'name'=>'TIBU'],
            ['id' => 821,'departments_id'=>54,   'name'=>'TOLEDO'],
            ['id' => 822,'departments_id'=>54,   'name'=>'VILLACARO'],
            ['id' => 823,'departments_id'=>54,   'name'=>'VILLA DEL ROSARIO'],
            ['id' => 824,'departments_id'=>63, 'name'=>'ARMENIA'],
            ['id' => 825,'departments_id'=>63,   'name'=>'BUENAVISTA'],
            ['id' => 826,'departments_id'=>63,   'name'=>'CALARCA'],
            ['id' => 827,'departments_id'=>63,   'name'=>'CIRCASIA'],
            ['id' => 828,'departments_id'=>63,   'name'=>'CORDOBA'],
            ['id' => 829,'departments_id'=>63,   'name'=>'FILANDIA'],
            ['id' => 830,'departments_id'=>63,   'name'=>'GENOVA'],
            ['id' => 831,'departments_id'=>63,   'name'=>'LA TEBAIDA'],
            ['id' => 832,'departments_id'=>63,   'name'=>'MONTENEGRO'],
            ['id' => 833,'departments_id'=>63,   'name'=>'PIJAO'],
            ['id' => 834,'departments_id'=>63,   'name'=>'QUIMBAYA'],
            ['id' => 835,'departments_id'=>63,   'name'=>'SALENTO'],
            ['id' => 836,'departments_id'=>66, 'name'=>'PEREIRA'],
            ['id' => 837,'departments_id'=>66,  'name'=>'APIA'],
            ['id' => 838,'departments_id'=>66,  'name'=>'BALBOA'],
            ['id' => 839,'departments_id'=>66,  'name'=>'BELEN DE UMBRIA'],
            ['id' => 840,'departments_id'=>66,   'name'=>'DOS QUEBRADAS'],
            ['id' => 841,'departments_id'=>66,   'name'=>'GUATICA'],
            ['id' => 842,'departments_id'=>66,   'name'=>'LA CELIA'],
            ['id' => 843,'departments_id'=>66,   'name'=>'LA VIRGINIA'],
            ['id' => 844,'departments_id'=>66,   'name'=>'MARSELLA'],
            ['id' => 845,'departments_id'=>66,   'name'=>'MISTRATO'],
            ['id' => 846,'departments_id'=>66,   'name'=>'PUEBLO RICO'],
            ['id' => 847,'departments_id'=>66,   'name'=>'QUINCHIA'],
            ['id' => 848,'departments_id'=>66,   'name'=>'SANTA ROSA DE CABAL'],
            ['id' => 849,'departments_id'=>66,   'name'=>'SANTUARIO'],
            ['id' => 850,'departments_id'=>68, 'name'=>'BUCARAMANGA'],
            ['id' => 851,'departments_id'=>68,  'name'=>'AGUADA'],
            ['id' => 852,'departments_id'=>68,  'name'=>'ALBANIA'],
            ['id' => 853,'departments_id'=>68,  'name'=>'ARATOCA'],
            ['id' => 854,'departments_id'=>68,  'name'=>'BARBOSA'],
            ['id' => 855,'departments_id'=>68,  'name'=>'BARICHARA'],
            ['id' => 856,'departments_id'=>68,  'name'=>'BARRANCABERMEJA'],
            ['id' => 857,'departments_id'=>68,  'name'=>'BETULIA'],
            ['id' => 858,'departments_id'=>68,   'name'=>'BOLIVAR'],
            ['id' => 859,'departments_id'=>68,   'name'=>'CABRERA'],
            ['id' => 860,'departments_id'=>68,   'name'=>'CALIFORNIA'],
            ['id' => 861,'departments_id'=>68,   'name'=>'CAPITANEJO'],
            ['id' => 862,'departments_id'=>68,   'name'=>'CARCASI'],
            ['id' => 863,'departments_id'=>68,   'name'=>'CEPITA'],
            ['id' => 864,'departments_id'=>68,   'name'=>'CERRITO'],
            ['id' => 865,'departments_id'=>68,   'name'=>'CHARALA'],
            ['id' => 866,'departments_id'=>68,   'name'=>'CHARTA'],
            ['id' => 867,'departments_id'=>68,   'name'=>'CHIMA'],
            ['id' => 868,'departments_id'=>68,   'name'=>'CHIPATA'],
            ['id' => 869,'departments_id'=>68,   'name'=>'CIMITARRA'],
            ['id' => 870,'departments_id'=>68,   'name'=>'CONCEPCION'],
            ['id' => 871,'departments_id'=>68,   'name'=>'CONFINES'],
            ['id' => 872,'departments_id'=>68,   'name'=>'CONTRATACION'],
            ['id' => 873,'departments_id'=>68,   'name'=>'COROMORO'],
            ['id' => 874,'departments_id'=>68,   'name'=>'CURITI'],
            ['id' => 875,'departments_id'=>68,   'name'=>'EL CARMEN DE CHUCURY'],
            ['id' => 876,'departments_id'=>68,   'name'=>'EL GUACAMAYO'],
            ['id' => 877,'departments_id'=>68,   'name'=>'EL PENON'],
            ['id' => 878,'departments_id'=>68,   'name'=>'EL PLAYON'],
            ['id' => 879,'departments_id'=>68,   'name'=>'ENCINO'],
            ['id' => 880,'departments_id'=>68,   'name'=>'ENCISO'],
            ['id' => 881,'departments_id'=>68,   'name'=>'FLORIAN'],
            ['id' => 882,'departments_id'=>68,   'name'=>'FLORIDABLANCA'],
            ['id' => 883,'departments_id'=>68,   'name'=>'GALAN'],
            ['id' => 884,'departments_id'=>68,   'name'=>'GAMBITA'],
            ['id' => 885,'departments_id'=>68,   'name'=>'GIRON'],
            ['id' => 886,'departments_id'=>68,   'name'=>'GUACA'],
            ['id' => 887,'departments_id'=>68,   'name'=>'GUADALUPE'],
            ['id' => 888,'departments_id'=>68,   'name'=>'GUAPOTA'],
            ['id' => 889,'departments_id'=>68,   'name'=>'GUAVATA'],
            ['id' => 890,'departments_id'=>68,   'name'=>'GUEPSA'],
            ['id' => 891,'departments_id'=>68,   'name'=>'HATO'],
            ['id' => 892,'departments_id'=>68,   'name'=>'JESUS MARIA'],
            ['id' => 893,'departments_id'=>68,   'name'=>'JORDAN'],
            ['id' => 894,'departments_id'=>68,   'name'=>'LA BELLEZA'],
            ['id' => 895,'departments_id'=>68,   'name'=>'LANDAZURI'],
            ['id' => 896,'departments_id'=>68,   'name'=>'LA PAZ'],
            ['id' => 897,'departments_id'=>68,   'name'=>'LEBRIJA'],
            ['id' => 898,'departments_id'=>68,   'name'=>'LOS SANTOS'],
            ['id' => 899,'departments_id'=>68,   'name'=>'MACARAVITA'],
            ['id' => 900,'departments_id'=>68,   'name'=>'MALAGA'],
            ['id' => 901,'departments_id'=>68,   'name'=>'MATANZA'],
            ['id' => 902,'departments_id'=>68,   'name'=>'MOGOTES'],
            ['id' => 903,'departments_id'=>68,   'name'=>'MOLAGAVITA'],
            ['id' => 904,'departments_id'=>68,   'name'=>'OCAMONTE'],
            ['id' => 905,'departments_id'=>68,   'name'=>'OIBA'],
            ['id' => 906,'departments_id'=>68,   'name'=>'ONZAGA'],
            ['id' => 907,'departments_id'=>68,   'name'=>'PALMAR'],
            ['id' => 908,'departments_id'=>68,   'name'=>'PALMAS DEL SOCORRO'],
            ['id' => 909,'departments_id'=>68,   'name'=>'PARAMO'],
            ['id' => 910,'departments_id'=>68,   'name'=>'PIEDECUESTA'],
            ['id' => 911,'departments_id'=>68,   'name'=>'PINCHOTE'],
            ['id' => 912,'departments_id'=>68,   'name'=>'PUENTE NACIONAL'],
            ['id' => 913,'departments_id'=>68,   'name'=>'PUERTO PARRA'],
            ['id' => 914,'departments_id'=>68,   'name'=>'PUERTO WILCHES'],
            ['id' => 915,'departments_id'=>68,   'name'=>'RIONEGRO'],
            ['id' => 916,'departments_id'=>68,   'name'=>'SABANA DE TORRES'],
            ['id' => 917,'departments_id'=>68,   'name'=>'SAN ANDRES'],
            ['id' => 918,'departments_id'=>68,   'name'=>'SAN BENITO'],
            ['id' => 919,'departments_id'=>68,   'name'=>'SAN GIL'],
            ['id' => 920,'departments_id'=>68,   'name'=>'SAN JOAQUIN'],
            ['id' => 921,'departments_id'=>68,   'name'=>'SAN JOSE DE MIRANDA'],
            ['id' => 922,'departments_id'=>68,   'name'=>'SAN MIGUEL'],
            ['id' => 923,'departments_id'=>68,   'name'=>'SAN VICENTE DE CHUCURI'],
            ['id' => 924,'departments_id'=>68,   'name'=>'SANTA BARBARA'],
            ['id' => 925,'departments_id'=>68,   'name'=>'SANTA HELENA DEL OPON'],
            ['id' => 926,'departments_id'=>68,   'name'=>'SIMACOTA'],
            ['id' => 927,'departments_id'=>68,   'name'=>'SOCORRO'],
            ['id' => 928,'departments_id'=>68,   'name'=>'SUAITA'],
            ['id' => 929,'departments_id'=>68,   'name'=>'SUCRE'],
            ['id' => 930,'departments_id'=>68,   'name'=>'SURATA'],
            ['id' => 931,'departments_id'=>68,   'name'=>'TONA'],
            ['id' => 932,'departments_id'=>68,   'name'=>'VALLE SAN JOSE'],
            ['id' => 933,'departments_id'=>68,   'name'=>'VELEZ'],
            ['id' => 934,'departments_id'=>68,   'name'=>'VETAS'],
            ['id' => 935,'departments_id'=>68,   'name'=>'VILLANUEVA'],
            ['id' => 936,'departments_id'=>68,   'name'=>'ZAPATOCA'],
            ['id' => 937,'departments_id'=>70,   'name'=>'SINCELEJO'],
            ['id' => 938,'departments_id'=>70,   'name'=>'BUENAVISTA'],
            ['id' => 939,'departments_id'=>70,   'name'=>'CAIMITO'],
            ['id' => 940,'departments_id'=>70,   'name'=>'COLOSO (RICAURTE)'],
            ['id' => 941,'departments_id'=>70,   'name'=>'COROZAL'],
            ['id' => 942,'departments_id'=>70,   'name'=>'CHALAN'],
            ['id' => 943,'departments_id'=>70,   'name'=>'GALERAS (NUEVA GRANADA)'],
            ['id' => 944,'departments_id'=>70,   'name'=>'GUARANDA'],
            ['id' => 945,'departments_id'=>70,   'name'=>'LA UNION'],
            ['id' => 946,'departments_id'=>70,   'name'=>'LOS PALMITOS'],
            ['id' => 947,'departments_id'=>70,   'name'=>'MAJAGUAL'],
            ['id' => 948,'departments_id'=>70,   'name'=>'MORROA'],
            ['id' => 949,'departments_id'=>70,   'name'=>'OVEJAS'],
            ['id' => 950,'departments_id'=>70,   'name'=>'PALMITO'],
            ['id' => 951,'departments_id'=>70,   'name'=>'SAMPUES'],
            ['id' => 952,'departments_id'=>70,   'name'=>'SAN BENITO ABAD'],
            ['id' => 953,'departments_id'=>70,   'name'=>'SAN JUAN DE BETULIA'],
            ['id' => 954,'departments_id'=>70,   'name'=>'SAN MARCOS'],
            ['id' => 955,'departments_id'=>70,   'name'=>'SAN ONOFRE'],
            ['id' => 956,'departments_id'=>70,   'name'=>'SAN PEDRO'],
            ['id' => 957,'departments_id'=>70,   'name'=>'SINCE'],
            ['id' => 958,'departments_id'=>70,   'name'=>'SUCRE'],
            ['id' => 959,'departments_id'=>70,   'name'=>'TOLU'],
            ['id' => 960,'departments_id'=>70,   'name'=>'TOLUVIEJO'],
            ['id' => 961,'departments_id'=>73,   'name'=>'IBAGUE'],
            ['id' => 962,'departments_id'=>73,   'name'=>'ALPUJARRA'],
            ['id' => 963,'departments_id'=>73,   'name'=>'ALVARADO'],
            ['id' => 964,'departments_id'=>73,   'name'=>'AMBALEMA'],
            ['id' => 965,'departments_id'=>73,   'name'=>'ANZOATEGUI'],
            ['id' => 966,'departments_id'=>73,   'name'=>'ARMERO (GUAYABAL)'],
            ['id' => 967,'departments_id'=>73,   'name'=>'ATACO'],
            ['id' => 968,'departments_id'=>73,   'name'=>'CAJAMARCA'],
            ['id' => 969,'departments_id'=>73,   'name'=>'CARMEN APICALA'],
            ['id' => 970,'departments_id'=>73,   'name'=>'CASABIANCA'],
            ['id' => 971,'departments_id'=>73,   'name'=>'CHAPARRAL'],
            ['id' => 972,'departments_id'=>73,   'name'=>'COELLO'],
            ['id' => 973,'departments_id'=>73,   'name'=>'COYAIMA'],
            ['id' => 974,'departments_id'=>73,   'name'=>'CUNDAY'],
            ['id' => 975,'departments_id'=>73,   'name'=>'DOLORES'],
            ['id' => 976,'departments_id'=>73,   'name'=>'ESPINAL'],
            ['id' => 977,'departments_id'=>73,   'name'=>'FALAN'],
            ['id' => 978,'departments_id'=>73,   'name'=>'FLANDES'],
            ['id' => 979,'departments_id'=>73,   'name'=>'FRESNO'],
            ['id' => 980,'departments_id'=>73,   'name'=>'GUAMO'],
            ['id' => 981,'departments_id'=>73,   'name'=>'HERVEO'],
            ['id' => 982,'departments_id'=>73,   'name'=>'HONDA'],
            ['id' => 983,'departments_id'=>73,   'name'=>'ICONONZO'],
            ['id' => 984,'departments_id'=>73,   'name'=>'LERIDA'],
            ['id' => 985,'departments_id'=>73,   'name'=>'LIBANO'],
            ['id' => 986,'departments_id'=>73,   'name'=>'MARIQUITA'],
            ['id' => 987,'departments_id'=>73,   'name'=>'MELGAR'],
            ['id' => 988,'departments_id'=>73,   'name'=>'MURILLO'],
            ['id' => 989,'departments_id'=>73,   'name'=>'NATAGAIMA'],
            ['id' => 990,'departments_id'=>73,   'name'=>'ORTEGA'],
            ['id' => 991,'departments_id'=>73,   'name'=>'PALOCABILDO'],
            ['id' => 992,'departments_id'=>73,   'name'=>'PIEDRAS'],
            ['id' => 993,'departments_id'=>73,   'name'=>'PLANADAS'],
            ['id' => 994,'departments_id'=>73,   'name'=>'PRADO'],
            ['id' => 995,'departments_id'=>73,   'name'=>'PURIFICACION'],
            ['id' => 996,'departments_id'=>73,   'name'=>'RIOBLANCO'],
            ['id' => 997,'departments_id'=>73,   'name'=>'RONCESVALLES'],
            ['id' => 998,'departments_id'=>73,   'name'=>'ROVIRA'],
            ['id' => 999,'departments_id'=>73,   'name'=>'SALDANA'],
            ['id' => 1000,'departments_id'=>73,   'name'=>'SAN ANTONIO'],
            ['id' => 1001,'departments_id'=>73,   'name'=>'SAN LUIS'],
            ['id' => 1002,'departments_id'=>73,   'name'=>'SANTA ISABEL'],
            ['id' => 1003,'departments_id'=>73,   'name'=>'SUAREZ'],
            ['id' => 1004,'departments_id'=>73,   'name'=>'VALLE DE SAN JUAN'],
            ['id' => 1005,'departments_id'=>73,   'name'=>'VENADILLO'],
            ['id' => 1006,'departments_id'=>73,   'name'=>'VILLAHERMOSA'],
            ['id' => 1007,'departments_id'=>73,   'name'=>'VILLARRICA'],
            ['id' => 1008,'departments_id'=>76, 'name'=>'Cali'],
            ['id' => 1009,'departments_id'=>76,  'name'=>'ALCALÁ'],
            ['id' => 1010,'departments_id'=>76,  'name'=>'ANDALUCÍA'],
            ['id' => 1011,'departments_id'=>76,  'name'=>'ANSERMANUEVO'],
            ['id' => 1012,'departments_id'=>76,  'name'=>'ARGELIA'],
            ['id' => 1013,'departments_id'=>76,   'name'=>'BOLÍVAR'],
            ['id' => 1014,'departments_id'=>76,   'name'=>'BUENAVENTURA'],
            ['id' => 1015,'departments_id'=>76,   'name'=>'Guadalajara de Buga'],
            ['id' => 1016,'departments_id'=>76,   'name'=>'BUGALAGRANDE'],
            ['id' => 1017,'departments_id'=>76,   'name'=>'CAICEDONIA'],
            ['id' => 1018,'departments_id'=>76,   'name'=>'CALIMA'],
            ['id' => 1019,'departments_id'=>76,   'name'=>'CANDELARIA'],
            ['id' => 1020,'departments_id'=>76,   'name'=>'CARTAGO'],
            ['id' => 1021,'departments_id'=>76,   'name'=>'DAGUA'],
            ['id' => 1022,'departments_id'=>76,   'name'=>'EL ÁGUILA'],
            ['id' => 1023,'departments_id'=>76,   'name'=>'EL CAIRO'],
            ['id' => 1024,'departments_id'=>76,   'name'=>'EL CERRITO'],
            ['id' => 1025,'departments_id'=>76,   'name'=>'EL DOVIO'],
            ['id' => 1026,'departments_id'=>76,   'name'=>'FLORIDA'],
            ['id' => 1027,'departments_id'=>76,   'name'=>'GINEBRA'],
            ['id' => 1028,'departments_id'=>76,   'name'=>'GUACARÍ'],
            ['id' => 1029,'departments_id'=>76,   'name'=>'JAMUNDÍ'],
            ['id' => 1030,'departments_id'=>76,   'name'=>'LA CUMBRE'],
            ['id' => 1031,'departments_id'=>76,   'name'=>'LA UNIÓN'],
            ['id' => 1032,'departments_id'=>76,   'name'=>'LA VICTORIA'],
            ['id' => 1033,'departments_id'=>76,   'name'=>'OBANDO'],
            ['id' => 1034,'departments_id'=>76,   'name'=>'PALMIRA'],
            ['id' => 1035,'departments_id'=>76,   'name'=>'PRADERA'],
            ['id' => 1036,'departments_id'=>76,   'name'=>'RESTREPO'],
            ['id' => 1037,'departments_id'=>76,   'name'=>'RIOFRÍO'],
            ['id' => 1038,'departments_id'=>76,   'name'=>'ROLDANILLO'],
            ['id' => 1039,'departments_id'=>76,   'name'=>'SAN PEDRO'],
            ['id' => 1040,'departments_id'=>76,   'name'=>'SEVILLA'],
            ['id' => 1041,'departments_id'=>76,   'name'=>'TORO'],
            ['id' => 1042,'departments_id'=>76,   'name'=>'TRUJILLO'],
            ['id' => 1043,'departments_id'=>76,   'name'=>'TULUÁ'],
            ['id' => 1044,'departments_id'=>76,   'name'=>'ULLOA'],
            ['id' => 1045,'departments_id'=>76,   'name'=>'VERSALLES'],
            ['id' => 1046,'departments_id'=>76,   'name'=>'VIJES'],
            ['id' => 1047,'departments_id'=>76,   'name'=>'YOTOCO'],
            ['id' => 1048,'departments_id'=>76,   'name'=>'YUMBO'],
            ['id' => 1049,'departments_id'=>76,   'name'=>'ZARZAL'],
            ['id' => 1050,'departments_id'=>81, 'name'=>'ARAUCA'],
            ['id' => 1051,'departments_id'=>81,  'name'=>'ARAUQUITA'],
            ['id' => 1052,'departments_id'=>81,   'name'=>'CRAVO NORTE'],
            ['id' => 1053,'departments_id'=>81,   'name'=>'FORTUL'],
            ['id' => 1054,'departments_id'=>81,   'name'=>'PUERTO RONDON'],
            ['id' => 1055,'departments_id'=>81,   'name'=>'SARAVENA'],
            ['id' => 1056,'departments_id'=>81,   'name'=>'TAME'],
            ['id' => 1057,'departments_id'=>85, 'name'=>'YOPAL'],
            ['id' => 1058,'departments_id'=>85,  'name'=>'AGUAZUL'],
            ['id' => 1059,'departments_id'=>85,  'name'=>'CHAMEZA'],
            ['id' => 1060,'departments_id'=>85,   'name'=>'HATO COROZAL'],
            ['id' => 1061,'departments_id'=>85,   'name'=>'LA SALINA'],
            ['id' => 1062,'departments_id'=>85,   'name'=>'MANI'],
            ['id' => 1063,'departments_id'=>85,   'name'=>'MONTERREY'],
            ['id' => 1064,'departments_id'=>85,   'name'=>'NUNCHIA'],
            ['id' => 1065,'departments_id'=>85,   'name'=>'OROCUE'],
            ['id' => 1066,'departments_id'=>85,   'name'=>'PAZ DE ARIPORO'],
            ['id' => 1067,'departments_id'=>85,   'name'=>'PORE'],
            ['id' => 1068,'departments_id'=>85,   'name'=>'RECETOR'],
            ['id' => 1069,'departments_id'=>85,   'name'=>'SABANALARGA'],
            ['id' => 1070,'departments_id'=>85,   'name'=>'SACAMA'],
            ['id' => 1071,'departments_id'=>85,   'name'=>'SAN LUIS DE PALENQUE'],
            ['id' => 1072,'departments_id'=>85,   'name'=>'TAMARA'],
            ['id' => 1073,'departments_id'=>85,   'name'=>'TAURAMENA'],
            ['id' => 1074,'departments_id'=>85,   'name'=>'TRINIDAD'],
            ['id' => 1075,'departments_id'=>85,   'name'=>'VILLANUEVA'],
            ['id' => 1076,'departments_id'=>86, 'name'=>'MOCOA'],
            ['id' => 1077,'departments_id'=>86,   'name'=>'COLON'],
            ['id' => 1078,'departments_id'=>86,   'name'=>'ORITO'],
            ['id' => 1079,'departments_id'=>86,   'name'=>'PUERTO ASIS'],
            ['id' => 1080,'departments_id'=>86,   'name'=>'PUERTO CAICEDO'],
            ['id' => 1081,'departments_id'=>86,   'name'=>'PUERTO GUZMAN'],
            ['id' => 1082,'departments_id'=>86,   'name'=>'PUERTO LEGUIZAMO'],
            ['id' => 1083,'departments_id'=>86,   'name'=>'SIBUNDOY'],
            ['id' => 1084,'departments_id'=>86,   'name'=>'SAN FRANCISCO'],
            ['id' => 1085,'departments_id'=>86,   'name'=>'SAN MIGUEL (LA DORADA)'],
            ['id' => 1086,'departments_id'=>86,   'name'=>'SANTIAGO'],
            ['id' => 1087,'departments_id'=>86,   'name'=>'LA HORMIGA (VALLE DEL GUA'],
            ['id' => 1088,'departments_id'=>86,   'name'=>'VILLAGARZON'],
            ['id' => 1089,'departments_id'=>88, 'name'=>'SAN ANDRES'],
            ['id' => 1090,'departments_id'=>88,   'name'=>'PROVIDENCIA'],
            ['id' => 1091,'departments_id'=>91, 'name'=>'LETICIA'],
            ['id' => 1092,'departments_id'=>91,   'name'=>'EL ENCANTO'],
            ['id' => 1093,'departments_id'=>91,   'name'=>'LA CHORRERA'],
            ['id' => 1094,'departments_id'=>91,   'name'=>'LA PEDRERA'],
            ['id' => 1095,'departments_id'=>91,   'name'=>'LA VICTORIA'],
            ['id' => 1096,'departments_id'=>91,   'name'=>'MIRITI-PARANA'],
            ['id' => 1097,'departments_id'=>91,   'name'=>'PUERTO ALEGRIA'],
            ['id' => 1098,'departments_id'=>91,   'name'=>'PUERTO ARICA'],
            ['id' => 1099,'departments_id'=>91,   'name'=>'PUERTO NARINO'],
            ['id' => 1100,'departments_id'=>91,   'name'=>'PUERTO SANTANDER'],
            ['id' => 1101,'departments_id'=>91,   'name'=>'TARAPACA'],
            ['id' => 1102,'departments_id'=>94, 'name'=>'PUERTO INIRIDA'],
            ['id' => 1103,'departments_id'=>94,   'name'=>'BARRANCO MINAS'],
            ['id' => 1104,'departments_id'=>94,   'name'=>'SAN FELIPE'],
            ['id' => 1105,'departments_id'=>94,   'name'=>'PUERTO COLOMBIA'],
            ['id' => 1106,'departments_id'=>94,   'name'=>'LA GUADALUPE'],
            ['id' => 1107,'departments_id'=>94,   'name'=>'CACAHUAL'],
            ['id' => 1108,'departments_id'=>94,   'name'=>'PANA PANA (CAMPO ALEGRE)'],
            ['id' => 1109,'departments_id'=>94,   'name'=>'MORICHAL (MORICHAL NUEVO)'],
            ['id' => 1110,'departments_id'=>95, 'name'=>'SAN JOSE DEL GUAVIARE'],
            ['id' => 1111,'departments_id'=>95,  'name'=>'CALAMAR'],
            ['id' => 1112,'departments_id'=>95,  'name'=>'EL RETORNO'],
            ['id' => 1113,'departments_id'=>95,   'name'=>'MIRAFLORES'],
            ['id' => 1114,'departments_id'=>97, 'name'=>'MITU'],
            ['id' => 1115,'departments_id'=>97,   'name'=>'CARURU'],
            ['id' => 1116,'departments_id'=>97,   'name'=>'PACOA'],
            ['id' => 1117,'departments_id'=>97,   'name'=>'TARAIRA'],
            ['id' => 1118,'departments_id'=>97,   'name'=>'PAPUNAUA (MORICHAL)'],
            ['id' => 1119,'departments_id'=>97,   'name'=>'YAVARATE'],
            ['id' => 1120,'departments_id'=>99, 'name'=>'PUERTO CARRENO'],
            ['id' => 1121,'departments_id'=>99,   'name'=>'LA PRIMAVERA'],
            ['id' => 1122,'departments_id'=>99,   'name'=>'SANTA RITA'],
            ['id' => 1123,'departments_id'=>99,   'name'=>'SANTA ROSALIA'],
            ['id' => 1124,'departments_id'=>99,   'name'=>'SAN JOSE DE OCUNE'],
            ['id' => 1125,'departments_id'=>99,   'name'=>'CUMARIBO']	

        ];


      	foreach ($cities as $city) {
      		DB::table('cities')->insert(['id' => $city['id'],'departments_id' => $city['departments_id'],'name' => $city['name']]);  
      	}
	}
}
